<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Iqb.Responses</PackageId>
    <Version>5.2.2-preview.1</Version>
    <Authors>IQB - Institut zur Qualitätsentwicklung im Bildungswesen</Authors>
    <Description>Native .NET response coding engine compatible with @iqb/responses.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/iqb-berlin/responses</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
