export const CODING_SCHEME_STATUS = {
  CODING_INCOMPLETE: 'CODING_INCOMPLETE',
  CODING_COMPLETE: 'CODING_COMPLETE',
  CODING_ERROR: 'CODING_ERROR',
  DERIVE_PENDING: 'DERIVE_PENDING',
  DERIVE_ERROR: 'DERIVE_ERROR',
  DISPLAYED: 'DISPLAYED',
  PARTLY_DISPLAYED: 'PARTLY_DISPLAYED',
  NOT_REACHED: 'NOT_REACHED',
  INVALID: 'INVALID',
  INTENDED_INCOMPLETE: 'INTENDED_INCOMPLETE',
  NO_CODING: 'NO_CODING',
  UNSET: 'UNSET',
  VALUE_CHANGED: 'VALUE_CHANGED'
} as const;

export const MANUAL_VALID_STATES = [
  CODING_SCHEME_STATUS.INVALID,
  CODING_SCHEME_STATUS.VALUE_CHANGED,
  CODING_SCHEME_STATUS.NO_CODING,
  CODING_SCHEME_STATUS.CODING_ERROR,
  CODING_SCHEME_STATUS.CODING_COMPLETE,
  CODING_SCHEME_STATUS.INTENDED_INCOMPLETE
] as const;

export const COPY_SOLVER_VALID_STATES = [
  CODING_SCHEME_STATUS.VALUE_CHANGED,
  CODING_SCHEME_STATUS.NO_CODING,
  CODING_SCHEME_STATUS.CODING_INCOMPLETE,
  CODING_SCHEME_STATUS.CODING_ERROR,
  CODING_SCHEME_STATUS.CODING_COMPLETE,
  CODING_SCHEME_STATUS.INTENDED_INCOMPLETE
] as const;

export const CONCAT_SUM_VALID_STATES = [
  CODING_SCHEME_STATUS.CODING_COMPLETE,
  CODING_SCHEME_STATUS.INTENDED_INCOMPLETE
] as const;

export const PARTLY_DISPLAYED_STATUSES = [
  CODING_SCHEME_STATUS.NOT_REACHED,
  CODING_SCHEME_STATUS.DISPLAYED,
  CODING_SCHEME_STATUS.PARTLY_DISPLAYED
] as const;

export const DERIVE_PENDING_STATUSES = [
  CODING_SCHEME_STATUS.CODING_INCOMPLETE,
  CODING_SCHEME_STATUS.DERIVE_PENDING
] as const;

export const VALID_STATES_TO_START_DERIVE_PENDING_CHECK = [
  CODING_SCHEME_STATUS.CODING_INCOMPLETE,
  CODING_SCHEME_STATUS.CODING_COMPLETE,
  CODING_SCHEME_STATUS.DERIVE_PENDING,
  CODING_SCHEME_STATUS.INTENDED_INCOMPLETE
] as const;
